services:
  glm-dash:
    build: .
    image: ghcr.io/ajianaz/glm-proxy-dashboard:latest
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - "traefik.http.routers.glm-dash.rule=Host(`gdash.ajianaz.dev`)"
      - traefik.http.routers.glm-dash.entrypoints=websecure
      - "traefik.http.routers.glm-dash.tls.certresolver=myresolver"
      - traefik.http.services.glm-dash.loadbalancer.server.port=80

networks:
  proxy:
    external: true
